name: services_weebi
version: 1.0.7
homepage: http://weebi.com
#publish_to: none #https://onepub.dev/api/xnxpsdavuh/
description: services
environment: 
  sdk: ">=2.19.6 <3.0.0"
dependencies: 
  collection: ^1.14.12
  sembast: ^3.1.0+2 #^3.3.1

  models_weebi: ^1.0.17
  
dev_dependencies: 
  test: ^1.16.0
