name: services_weebi
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  models_weebi:
    path: ../models_weebi
  sembast: ^3.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
